//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Faculty
    {
      //  [Table("faculty")]
        public int Id { get; set; }

        [Column("first_name")]
        public string Name { get; set; }
        public string Teachers { get; set; }
    
        public virtual Faculty Faculty1 { get; set; }
        public virtual Faculty Faculty2 { get; set; }
    }
}
