//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsInformation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> Entering_year { get; set; }
        public Nullable<System.DateTime> Graduation_Year { get; set; }
        public string Group { get; set; }
        public Nullable<double> Average_Mark { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string Status { get; set; }
    }
}
